package:
  name: tectool
  version: "0.2"

source:
  git_url: https://git.scicore.unibas.ch/zavolan_public/TECtool.git
  git_rev: v0.2

build:
  number: 0

requirements:
  build:
    - python
  run:
    - python 3.6.2
    - htseq 0.9.1
    - pybedtools 0.7.10
    - bzip2
    - pyfasta==0.5.2
    - scikit-learn==0.19.0

test:
  imports:
    - sys
    - HTSeq
    - math
    - argparse
    - itertools
    - collections
    - pybedtools
    - pyfasta
    - pandas
    - matplotlib
    - sklearn
    - scipy
    - random
    - numpy
    - copy
    - csv
    - functools

about:
  home: http://tectool.unibas.ch/
  license: MIT
  license_file: https://git.scicore.unibas.ch/zavolan_public/TECtool/blob/master/LICENSE
