package:
  name: tectool
  version: "0.2"
source:
  git_url: https://git.scicore.unibas.ch/zavolan_public/TECtool.git
#  git_rev: v0.2
build:
  # If the installation is complex, or different between Unix and Windows, use
  # separate bld.bat and build.sh files instead of this key.  Add the line
  skip: True  # [py<34]
  # "skip: True  # [not win]" to limit to Windows.
  script: python setup.py install --single-version-externally-managed --record=record.txt
  number: 0
channels:
  - conda-forge
  - bioconda
  - fgypas
requirements:
  build:
    - python 3.6.2
  run:
    - python
    - htseq 0.9.1
    - bedtools 2.26
    - pybedtools 0.7.10
    - bzip2
    - pyfasta 0.5.2
    - scikit-learn 0.19.0
    - pandas 0.20.3
    - matplotlib 2.0.2
test:
  imports:
    - sys
    - HTSeq
    - os
    - math
    - argparse
    - itertools
    - collections
    - pybedtools
    - pyfasta
    - pandas
    - matplotlib
    - sklearn
    - scipy
    - random
    - numpy
    - copy
    - csv
    - functools
    - tectool
    - tectool.analysis_unit
    - tectool.annotation
    - tectool.bayes_classifier
    - tectool.detailed_alignment
    - tectool.exon
    - tectool.feature_counts
    - tectool.gene
    - tectool.machine_learning_unit
    - tectool.split_event
    - tectool.transcript
about:
  home: http://tectool.unibas.ch/
  summary: TECtool is a method that uses mRNA and 3' end sequencing data to identify novel terminal exons.
  license: MIT
  license_file: LICENSE
